on: pull_request
name: Pull Request Updates
jobs:
  pr-label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0.0
    - uses: actions/labeler@v2.0.0
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
      with:
        configuration-path: .github/PULL_REQUEST_LABELS.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
